### ISSUE TITLE
The SelfX.lnk file is "malicious"

### ISSUE THREAD

**Issue by jtonzi** [damienvanrobaeys/SelfX#1]
I'm sure you don't mean for the file to be flagged, but Defender and multiple other anti-virus programs are quarantining your SelfX.lnk as a virus.
What's in the lnk file? What's it referencing? (I'm guessing it's important to the whole implementation of this tool, so it may be necessary)

**Comment by damienvanrobaeys** [comment]
I will check that.
For now i didn't have this kind of feedback.
How did you install it ? Manually or with Intune ?

**Comment by damienvanrobaeys** [comment]
I found the issue, the link run cmd.exe and powershell.
In the new install_tool i generate directly the lnk.
Now when I download the ZIP, it does not detect it as a trojan.

**Comment by damienvanrobaeys** [comment]
Would it be possible to confirm that it's working now ?
Then i will close the issue

**Comment by jtonzi** [comment]
Sorry about the delay. Works great now. Thank you!

**Comment by damienvanrobaeys** [comment]
No worries and thanks for your good feedback about the issue.
